# Generated by Django 5.2.8 on 2025-12-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_desc', models.CharField(max_length=200)),
                ('item_name', models.IntegerField()),
            ],
        ),
    ]
